@startuml IgualApp
|Inicio de Sesión|
start
:Permite a los usuarios ingresar sus credenciales para acceder a la aplicación.;
if (¿Usuario registrado?) then (No)
:Mostrar Pantalla Principal;
:Mostrar Pantalla de Registro;
:Permite a los nuevos usuarios crear una cuenta en la aplicación.;
:Mostrar Pantalla de Recuperación de Contraseña;
:Permite al usuario recibir un correo para restablecer su contraseña.;
else (Sí)
|Pantalla Principal|
:Ver Visión General de la Aplicación;
:Acceder a Recursos Educativos;
:Participar en la Comunidad;
:Reportar Incidentes de Racismo;
:Explorar Estadísticas y Datos;
:Administrar Perfil de Usuario;
:Configurar Preferencias;
:Ver Notificaciones Importantes;
:Explorar Actualizaciones y Novedades;
|Recursos Educativos|
:Acceso a Artículos, Videos, Libros, etc.;
:Aprender sobre Igualdad y Diversidad;
|Comunidad|
:Participar en Discusiones y Colaborar en Iniciativas;
:Compartir Experiencias y Conocimientos;
|Módulo de Denuncia de Incidentes|
:Permite a los usuarios reportar casos de racismo;
:Registro de Ubicación y Detalles de Incidentes;
|Estadísticas y Datos|
:Visualización de Estadísticas Relacionadas con el Racismo;
:Historias de Éxito y Avances;
|Perfil de Usuario|
:Gestionar Perfil y Preferencias;
|Notificaciones|
:Ver Notificaciones Importantes y Alertas;
|Actualizaciones y Novedades|
:Información sobre Nuevos Recursos y Eventos;
endif
@enduml
